baseURL = 'https://atelierartlessons.com/'
languageCode = 'en-us'
title = 'Atelier Art Lessons'
theme = "alpha"


[params]
  description = "Atelier Art Lessons. Art for everyone."
#   images = ["images/pic01.jpg"]
  author = "Jessica Parker <jessica@atelierartlessons.com>"
  copyright = "&copy; Atelier Art Lessons, LLC. All rights reserved."
  mainSections = ["about"]

### Footer Social Media Links ###
# [[params.share]]
# title = "facebook"
# icon = "fa-facebook-f" # fontawesome icons https://fontawesome.com/icons?d=gallery&s=brands
# link = "https://www.facebook.com/"

# [[params.share]]
# title = "twitter"
# icon = "fa-twitter"
# link = "https://twitter.com/"

[[params.share]]
title = "instagram"
icon = "fa-instagram"
link = "https://www.instagram.com/atelierartlessons/"



### For Pages the .RelPermalink must match the menu .URL
### For sections the name/directory must match the menu .Identifier
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
  [[menu.main]]
    identifier = "Classes"
    name = "Classes"
    url = "/classes/" 
  [[menu.main]]
    identifier = "Schedule"
    name = "Schedule"
    url = "/schedule/" 
  [[menu.main]]
    identifier = "summer-camps"
    name = "Summer Camps"
    url = "/summercamps/"
  [[menu.main]]
    name = "Policies"
    url = "/policies/"
  [[menu.main]]
    name = "Payments"
    url = "/payments/"